### ISSUE TITLE
How do you get the Payment token ?

### ISSUE THREAD

**Issue by MaximeGaudin** [paymill/paymill-java#63]
In the payment/transaction sample, you use a fixed token (for instance when calling the `paymentService.createWithToken`). If I get your API right, the token is generated using the card information. How can I get this token using the Java API ?

**Comment by nikoloff** [comment]
See how from the tests:
https://github.com/paymill/paymill-java/blob/master/src/test/java/com/paymill/services/TransactionServiceTest.java#L57-L64

**Comment by MaximeGaudin** [comment]
Thanks, but why is this method not merged into the Java API ?
Also, I does not look production ready to me :  

* `https://test-token.paymill.com/`
* `transaction.mode=CONNECTOR_TEST`

Is there an official documentation about how to generate the token ?

**Comment by nikoloff** [comment]
Creating token is not part of the paymill-java wrapper.
The token must be generated on the client side using the PAYMILL bridge. If you want to generate the token on your server, the server must be PCI compliant.

For more info how to generate the token take a look at this page https://developers.paymill.com/guides/reference/bridge.html

**Comment by MaximeGaudin** [comment]
I don't want to generate the token myself, I just want a simple way to get it. 

I am developping an API and I obviously cannot integrate the (javascript, client side) bridge. 
I however need to retrieve this token and the link you provided documents how to generate it using only the bridge script (which I don't want to reverse engineer).

So why is the HTTP call not integrated in the Java-wrapper ? Why is the call looks so test-oriented ? I understand I have to replace `https://test-token.paymill.com` by `https://token.paymill.com` to generate real token but is the a clean REST documentation available ?

**Comment by nikoloff** [comment]
If this call was integrated in the java-wrapper each backend, which use the java wrapper must be PCI compliant. The idea of PAYMILL is to allow merchants to process payments, without been PCI compliant. The credit card details are sent from the client (browser) directly to our server.

This call will not be part of the java wrapper. There is not REST docu for this part, because it is not meant to be used the way you want.

What are you trying to do?

**Comment by stoilkov** [comment]
@MaximeGaudin  you should not generate a token from your backend. To do this, you should send the actual card information to your server, which means you need a high level of PCI certification. 
Generate the token either with the bridge (web) or with the mobile SDKs. 
If you have a use case that requires you to generate the tokens from your backend, please contact support@paymill.com and explain your use case.

**Comment by MaximeGaudin** [comment]
Ok, I did not understood the card data cannot even bounce from my server to yours. I will figure out a way, thanks for your time :)
