### ISSUE TITLE
Fix release 5.1.4

### ISSUE THREAD

**Issue by hoegertn** [paymill/paymill-java#70]
The release 5.1.4 is available in Github releases but there are no commits and it is not on Maven central so it is not usable....

**Comment by hoegertn** [comment]
@Iarwa1n ping

**Comment by hoegertn** [comment]
@larwa1n any ETA on this?

**Comment by Plato2013** [comment]
Hello,

sorry for the delay. The library should now be available trough Maven as version 5.1.6
